version: '2'
services:
    pixsell_w-app:
        image: pixsell_w
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pixsell_w-mysql:3306/pixsell_w?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pixsell_w-mysql:
        extends:
            file: mysql.yml
            service: pixsell_w-mysql
